stages:
  - test
  - build
  - deploy

test-stage:
  stage: test
  image: python:3.11
  script:
    - pip install -r requirements.txt
    - export PYTHONPATH="${PYTHONPATH}:."
    - pytest tests/

build-stage:
  stage: build
  tags: 
    - shell-docker
  script:
    - docker build -t task-manager .

deploy-staging:
  stage: deploy
  only:
    - staging
  script:
    - echo "Deploying to staging..."
    - ssh $STAGING_USER@$STAGING_HOST 'docker pull ... && docker run ...'

deploy-prod:
  stage: deploy
  only:
    - main
  when: manual
  script:
    - echo "Deploying to production..."
    - ssh $PROD_USER@$PROD_HOST 'docker pull ... && docker run ...'
