stages:
  - test
  - build
  - deploy
variables:
  DOCKER_DRIVE: overlay2

test-stage:
  stage: test
  image: python:3.11
  script:
    - pip install -r requirements.txt
    - export PYTHONPATH="${PYTHONPATH}:."
    - pytest tests/

build-stage:
  stage: build
  image: docker:latest
  script:
    - docker build -t task-manager .

deploy-staging:
  stage: deploy
  only:
    - staging
  script:
    - echo "Deploying to staging..."
    - ssh $STAGING_USER@$STAGING_HOST 'docker pull ... && docker run ...'

deploy-prod:
  stage: deploy
  image: docker:latest
  script:
    - docker stop task-manager || true
    - docker rm task-manager || true
    - docker run -d -p 32771:8000 --name task-manager

